[package]
name = "mapping-suites-rs"
version = "0.0.1"
authors = ["Emily Matheys <emilymatt96@gmail.com>"]
description = "A collection of SLAM suites, for use with mapping-algorithms-rs"
edition = "2021"
rust-version = "1.67"
license = "MIT"
readme = "../../README.md"
categories = ["slam", "robotics", "algorithms"]
keywords = ["algorithms", "mathematics", "science"]
include = ["../LICENSE", "**/*.rs", "Cargo.toml"]

[package.metadata.docs.rs]
all-features = true

[lib]

[features]
default = ["std"]
std = ["nalgebra/std"]
2d = []
3d = []
cuda = ["nalgebra/cuda", "bindgen", "cc"]

[dependencies]
mapping-algorithms-rs = { path = "../algorithms" }
log = "0.4.19"
nalgebra = { version = "0.32.3", default-features = false }
tracing = "0.1.37"

[build-dependencies]
bindgen = { version = "0.66.1", optional = true }
cc = { version = "1.0.79", optional = true }
