version: 2
updates:
  # This is mostly for actions/checkout
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # This is actually for cargo crates
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
