[workspace]
resolver = "1" # Prevent duplicate crates
members = ["crates/algorithms", "crates/suites"]

[profile.dev]
opt-level = 1

# Compile external dependencies with higher opt level
[profile.dev.package."*"]
opt-level = 2

[profile.release]
opt-level = 2
