[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
authors = ["Emily Matheys <emilymatt96@gmail.com>"]
description = "A collection of algorithms and suites for SLAM purposes"
edition = "2024"
license = "MIT"
categories = ["algorithms", "science", "science::robotics"]
keywords = ["algorithms", "mathematics", "science"]
repository = "https://github.com/EmilyMatt/mapping-rs"

[workspace.dependencies]
log = { version = "0.4.25", default-features = false }
nalgebra = { version = "0.35.0", default-features = false, features = ["libm"] }
num-traits = { version = "0.2.19", default-features = false, features = ["libm"] }
rand = { version = "0.10.2", default-features = false }
thiserror = { version = "2.0.11", default-features = false }
tracing = { version = "0.1.41", default-features = false, features = ["attributes"] }

mapping-algorithms = { path = "crates/mapping-algorithms" }
mapping-suites = { path = "crates/mapping-suites" }
