[workspace]
resolver = "2"
members = ["crates/algorithms", "crates/suites"]

[profile.dev]
opt-level = 1

# Compile external dependencies with higher opt level
[profile.dev.package."*"]
opt-level = 3

[profile.test]
opt-level = 3

[profile.release]
opt-level = 3
