[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
unsound = "deny"

[bans]
multiple-versions = "deny"
skip = [
    { name = "cc" },
    { name = "bindgen" },
    { name = "syn" },
    { name = "bitflags" }
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "neither"
copyleft = "deny"
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "MIT",
    "ISC",
    "BSD-3-Clause",
]
exceptions = [
{ allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]
