[advisories]

# The various windows crates should be safe
# For nalgebra simba, bitflags are required
# For syn, it is a dev dependency
[bans]
multiple-versions = "deny"
skip = ["bitflags", "syn",
    "windows_x86_64_msvc", "windows_x86_64_gnu", "windows_x86_64_gnullvm",
    "windows_i686_msvc", "windows_i686_gnu", "windows_i686_gnullvm",
    "windows_aarch64_msvc", "windows_aarch64_gnullvm",
    "windows-targets", "windows-sys"]

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
exceptions = [
    { name = "unicode-ident", allow = ["Unicode-DFS-2016"] }, # unique license
]
unused-allowed-license = "allow"
confidence-threshold = 0.93
allow = [
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MIT",
    "ISC"
]
