[advisories]

[bans]
multiple-versions = "deny"
skip = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
unused-allowed-license = "allow"
allow = [
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MIT",
    "Unicode-3.0"
]
