[package]
name = "mapping-algorithms-rs"
version = "0.0.1"
authors = ["Emily Matheys <emilymatt96@gmail.com>"]
description = "A collection of pure-rust algorithms in popular use for SLAM purposes"
edition = "2021"
rust-version = "1.67"
license = "MIT"
readme = "../../README.md"
categories = ["slam", "robotics", "algorithms"]
keywords = ["algorithms", "mathematics", "science"]
include = ["../LICENSE", "**/*.rs", "Cargo.toml"]

[package.metadata.docs.rs]
all-features = true

[lib]

[features]
default = ["std"]
std = ["nalgebra/std", "tracing?/std", "rand/std", "rand/std_rng"]
tracing = ["dep:tracing"]
cuda = ["nalgebra/cuda", "bindgen", "cc"]

[dependencies]
log = { version = "0.4.19", default-features = false }
nalgebra = { version = "0.32.3", default-features = false }
num-traits = { version = "0.2.16", default-features = false }
tracing = { version = "0.1.37", default-features = false, optional = true }

[dev-dependencies]
rand = { version = "0.8.5", default-features = false }

[build-dependencies]
bindgen = { version = "0.66.1", default-features = false, optional = true }
cc = { version = "1.0.83", default-features = false, optional = true }
