name: MacOS Build + Tests

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - uses: taiki-e/install-action@nextest
      - name: Test
        run: cargo test --all -- --nocapture
