name: Code Coverage

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: windows-latest # Because wayland crates fucks up the Linux build with unstable attribute use
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov
      - name: Generate Code Coverage
        run: cargo llvm-cov --all --codecov --output-path codecov.json
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: codecov.json
          fail_ci_if_error: true
