name: Licenses and CVEs
on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Deny
        run: cargo install cargo-deny
      - name: Check Deny
        run: cargo deny --log-level info check
