name: Mandatory Pull Request Checks

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Clippy
        run: cargo clippy --all

  check-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Deny
        run: cargo install cargo-deny
      - name: Check Deny
        run: cargo deny --log-level info check

  check-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Doc
        run: cargo doc --all

  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Rustfmt
        run: cargo fmt --all --check

  build-no_std:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --all --no-default-features --features=pregenerated
      - uses: taiki-e/install-action@nextest
      - name: Test
        run: cargo test --all --no-default-features --features=pregenerated -- --nocapture

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - uses: taiki-e/install-action@nextest
      - name: Test
        run: cargo test --all -- --nocapture

  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - uses: taiki-e/install-action@nextest
      - name: Test
        run: cargo test --all -- --nocapture

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - uses: taiki-e/install-action@nextest
      - name: Test
        run: cargo test --all -- --nocapture
