name: Build
on: [pull_request]
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Clippy
        run: cargo clippy --all-targets --all-features
      - name: Check Rustfmt
        run: cargo fmt --check
      - name: Check Deny
        run: cargo deny check
