name: Release Flow

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  release-plz:
    name: Release with release-plz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
